version: '3'

services:
  db:
    image: postgres:10
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    env_file:
      - env_file
    networks:
      - db_nw

  aiohttp-app:
    build: .
    env_file:
      - env_file
    volumes:
      - .:/opt/services/aiohttp-app/src
    networks:
      - db_nw
      - web_nw
    depends_on:
      - db

  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - web_nw
    depends_on:
      - aiohttp-app


networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge
volumes:
  dbdata: